### ISSUE TITLE
Global update policy ignored by aether [PAXURL-342]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.url#170]
**[ŁukaszD](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:b8f5c399-d2b6-444f-937c-b3a2316153dd)** created **[PAXURL-342](https://ops4j1.jira.com/browse/PAXURL-342)** 

According to documentation it is possible to use global update policy to control how often repository metadata will be fetched before resolving artifacts.

Based on documentation and found pieces of information I've tried following:

* Setting globalUpdatePolicy = never
* Setting per repository updateSnapshots, updateReleases, update in different combination
* Disabling all but one repository for pulling in metadata<br /> .. but aether always goes to all repositories and collects maven-metadata even if its told not to. What is even worse it does scan remote repositories for internal artifacts and currently there is no way to disable this (since none of provided switches influences resolver).

Reproducing issue:

* Setting repository configuration as described above
* Setting log level to DEBUG (http output goes to {{shaded.org.apache.http.impl.conn.Wire}}cateogry)
* Trying to resolve an artifact metadata by adding for example feature with version range such `mvn:org.code-house.jackson/features/[2.min,3.min)/xml/features`

After an attept to show information about features there should be resolution trigger which will cause collecting metadata from remote repos. By applied configuration such scan requests should not go outside or go through just one mirror repositry, but they always go to every repo defined.

Explaination why level of this issue is set a critical - it exposes vulnerable information about internal artifact group/artifact information. Only one workaround is to disable completely external repos and rely only on centralized proxy.<br /> There is also performance implication of that, projects with long snapshot lists or version ranges defined resolve much longer than they should.<br /> Please verify if this matches "critical" flag and correct it if you consider this other priority bug.

---

**Affects:** 2.4.7, 2.5.2
Votes: 0, Watches: 2

**Comment by grgrzybek** [comment]
Indeed - global update/checksum policy was overriding locally (per-repository) policies. I've reviewed it in #417
