### ISSUE TITLE
Detach configuration from java.net.URL [PAXURL-172]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.url#219]
**[Toni Menzel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e7e50a9b-1dd6-45df-b446-7b0e65306e2b)** created **[PAXURL-172](https://ops4j1.jira.com/browse/PAXURL-172)** 

---

**Fixed in:** 2.x
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
@tonit feel free to reopen and elaborate on this issue.
