### ISSUE TITLE
Ability to retrieve a available list of a specific maven artifact's versions via ( with given groupId and artifactId ) [PAXURL-247]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.url#287]
**[Dan Tran](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:1e20f838-c2f7-46a9-84ec-b2507458c9af)** created **[PAXURL-247](https://ops4j1.jira.com/browse/PAXURL-247)** 

Use case: I have agent that periodically poll a maven repository looking for upgrade indicator for a particular app which has known maven coordinate

To do i need ability to download maven-metadata.xml of an artifact ( ex [http://central.maven.org/maven2/org/ops4j/pax/url/pax-url-eather/maven-metadata.xml](http://central.maven.org/maven2/org/ops4j/pax/url/pax-url-eather/maven-metadata.xml)

The attached patch allows me do so with changes to pax-url's mvn url

from

mvn-uri := 'mvn:' [ repository-url '!' ] group-id '/' artifact-id [ '/' [version](https://ops4j1.jira.com/wiki/display/paxurl/version) [ '/' [type](https://ops4j1.jira.com/wiki/display/paxurl/type) [ '/' classifier ] ] ] ]

to

mvn-uri := 'mvn:' [ repository-url '!' ] group-id '/' artifact-id [ '/' [version](https://ops4j1.jira.com/wiki/display/paxurl/version) [ '/' [type](https://ops4j1.jira.com/wiki/display/paxurl/type) [ '/' classifier ] '/' [fileName](https://ops4j1.jira.com/wiki/display/paxurl/fileName) ] ] ] ]

---

**Affects:** 1.3.7, 1.4.2, 1.5.2, 1.6.0
**Attachments:**
* [KARAF-688.diff](https://ops4j1.jira.com/secure/attachment/12430/KARAF-688.diff)

Votes: 0, Watches: 3

**Comment by grgrzybek** [comment]
Pax URL should not be used to download arbitrary files from Maven repository. pax-url-aether uses maven-resolver library to _resolve_ repository content and `maven-metadata.xml` file is an internal implementation detail of the resolution process.

What you need is not a special `mvn:` syntax enhancement, but simply direct invocation of Maven Resolver API, where you can simply get a list of available versions from Maven repository. See [Maven Resolver API](https://maven.apache.org/resolver/apidocs/org/eclipse/aether/RepositorySystem.html).
