### ISSUE TITLE
Settings properties not expanded by Aether [PAXURL-266]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.url#301]
**[Dale Peakall](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:769df2a7-c9db-4691-b91c-72d2bbeafcdb)** created **[PAXURL-266](https://ops4j1.jira.com/browse/PAXURL-266)** 

The maven settings.xml file can include substitution properties which are then referenced in other parts of the settings.xml file using ant syntax `${propertyName}`. Aether doesn't appear to expand these properties correctly.

For example, if the repository URL is specified in a property then the following error is returned:

```java
[main] ERROR org.ops4j.pax.url.mvn.internal.AetherBasedResolver - invalid repository URLs
java.net.MalformedURLException: no protocol: ${snapshotsRepoUrl}/
```

---

**Affects:** 2.0.0
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
It works already.
