### ISSUE TITLE
pax-url-wrap should not require osgi.function and osgi.promise

### ISSUE THREAD

**Issue by jbonofre** [ops4j/org.ops4j.pax.url#388]
Both osgi.function & osgi.promise should be optional or private for pax-url-wrap.

**Comment by grgrzybek** [comment]
promise should NOT be optional because it's required by static field in bndlib's `Analyzer`.

**Comment by jbonofre** [comment]
FYI, I fixed the issue in Karaf 4.2 by adding util.function and util.promise in framework feature (as I did for Karaf 4.3).

**Comment by grgrzybek** [comment]
ah, great - having it in `framework` is the best idea ;) these two became quite essential bundles.

**Comment by jbonofre** [comment]
@grgrzybek I think we can close this issue or do you think we should do something on PAX URL ?

**Comment by grgrzybek** [comment]
Hmm, pax-url-wrap should normally import the packages, but IMO pax-url-wrap/uber should private package them (together with bndlib).

**Comment by jbonofre** [comment]
OK, I will do the fix then. Thanks.
