### ISSUE TITLE
Support ability to completely disable remote artifact resolution

### ISSUE THREAD

**Issue by mattrpav** [ops4j/org.ops4j.pax.url#395]
Use case:

 All bundles and feature files are made available locally. During boot, if a bundle or feature definition is missing, the featuresBoot should fail, and no remote or local (.m2/repository) resolution should occur.

Attempted this configuration, and artifacts are still resolved from .m2/repository

```
org.ops4j.pax.url.mvn.globalUpdatePolicy = never           # should disable updating?
org.ops4j.pax.url.mvn.localRepository=local-repo-cache     # set to a relative path that is empty (should not resolve .m2/repository)
org.ops4j.pax.url.mvn.repositories=                        # empty no repositories listed (should not resolve any remote repos)
org.ops4j.pax.url.mvn.useFallbackRepositories=false        # don't use the wonky hard-coded fallback repositories
```

**Comment by mattrpav** [comment]
Resolved.  Point to a settings.xml file with offline set to 'true'

**Comment by jbonofre** [comment]
Yeah, you just have to use `offline` in the aether/maven config.
