### ISSUE TITLE
bndlib 5.2.0 leads to high memory overhead when loading JARs

### ISSUE THREAD

**Issue by mdonkers** [ops4j/org.ops4j.pax.url#399]
org.ops4j.pax.url upgraded the bnd lib from 2.3.0 to 5.2.0 (see https://github.com/ops4j/org.ops4j.pax.url/commit/2ca206e3fc0d8fdd70ef9a4437a440e1b945f8e6 ).

With this update of bnd lib, a issue was introduced (since bnd tools 4.0.0) where even loading relatively small JAR files can lead to major memory overhead (JAR file of 11 Mb needs 350+ Mb to get loaded). In memory-constrained environments, for example running a Karaf application on Kubernetes with memory limits applied, this will lead to issues where the app goes out of memory or gets killed.
The problem was flagged with bnd lib here: https://github.com/bndtools/bnd/issues/4901
And they already provided a fix: https://github.com/bndtools/bnd/commit/89743f9ed2554981934b71df301572665ef95dcd
However at the moment of writing there is no new version of bnd yet including the fix (and thus neither is there for org.ops4j.pax.url).

Requesting to update those dependencies whenever a fix is available and released (as the Karaf project has a dependency on org.ops4j.pax.url and where we are actually experiencing that issue).

**Comment by jbonofre** [comment]
Still waiting for bndlib 6.1.0 to update in pax-url.

**Comment by jbonofre** [comment]
bndlib 6.1.0 has been released. I will move forward with the update and pax-url release.
