### ISSUE TITLE
pax-url-aether bundle will be stopped on malformed settings.xml

### ISSUE THREAD

**Issue by FelixMarxIBM** [ops4j/org.ops4j.pax.url#409]
We noticed that the pax-url-bundle will be stopped on startup when a malformed settings.xml is present.
In our example, the global `/home/user/.m2/settings.xml` was malformed but our own custom settings.xml was correct and would be introduced as soon as the ConfigAdmin is present.
Due to the nature of the bundle failing on startup, the ManagedService was never registered and the custom settings.xml was not reloaded.

Added a PR to only log such errors and continue with the Service registration [org.ops4j.pax.url!408](https://github.com/ops4j/org.ops4j.pax.url/pull/408)

**Comment by grgrzybek** [comment]
Closed with #408
