### ISSUE TITLE
New url handler: ivy [PAXURL-5]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.url#41]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** created **[PAXURL-5](https://ops4j1.jira.com/browse/PAXURL-5)** 

---

Votes: 0, Watches: 2

**Comment by grgrzybek** [comment]
Anyone interested in `ivy:` protocol, please reopen if needed. For now I'm closing it.
