### ISSUE TITLE
AetherBasedResolver memory leak caused by sessions map

### ISSUE THREAD

**Issue by bhe-talendbj** [ops4j/org.ops4j.pax.url#415]
From our heap dump, retain size of org.ops4j.pax.url.mvn.internal.AetherBasedResolver is more than 1.1G, sessions map contains lots of entries.

From source code, newSession(LocalRepository repo) will retrieve cached RepositorySystemSession by Key: LocalRepository which type is "simple".

While in method: releaseSession(RepositorySystemSession session), Key: LocalRepository which type is "pax-url".

So the sessions map will grow forever, because the key which is used to retrieve the cache is not equals to cached entries' key.

**Comment by grgrzybek** [comment]
Great catch @bhe-talendbj.
I just got back to Pax URL to check something related to pax-url-war, but I was thinking for a long time about moving pax-url-aether to new Maven Resolver.

**Comment by bhe-talendbj** [comment]
> but I was thinking for a long time about moving pax-url-aether to new Maven Resolver.

Seems great. Thank you for checking this so quickly.

**Comment by grgrzybek** [comment]
Related to #413.
