### ISSUE TITLE
New url handler: composite [PAXURL-13]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.url#49]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** created **[PAXURL-13](https://ops4j1.jira.com/browse/PAXURL-13)** 

It may be useful to have an url handler that can combine bundles into uber(composite) bundle.<br /> E.g. dp:some_url, where some_url points to a file that lists the urls of the bundle/jars that makes up the composite bundle.

The url handler will create a bundle out of the listed bundles/jars by combining contents and osgi headers from manifest.mf.

Issues to think about:

* shall listed resources be expanded or included via Bundle-ClassPath
* shall it support Include/Exclude resources
* what happens with split packages
* what happens with duplicate classes/resources
* what about duplicated export/import with different versions.

---

Votes: 0, Watches: 0

**Comment by grgrzybek** [comment]
For now I'm closing it. There are better ways to produce an uber bundle (both with maven-bundle-plugin and bnd-maven-plugin). If anyone feels it should be implemented, please reopen (providing a PR if possible).
