### ISSUE TITLE
New url handler: Deployment Package (dp:) [PAXURL-14]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.url#50]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** created **[PAXURL-14](https://ops4j1.jira.com/browse/PAXURL-14)** 

Implement an url handler that can create deployment packages as specified by deployment admin spec out of a specified instruction file.<br /> Best will be to provide a tool ala bnd that can create the deployment package that can be used by this url handler but also can be used outside like for example command line or a maven plugin.

---

Votes: 1, Watches: 1

---
**Referenced issues**

**relates to:**
* ops4j/org.ops4j.pax.swissbox#27 - Minimal support the creating of deployment packages [PAXSB-14]

**Comment by grgrzybek** [comment]
@tonit do you think it's still valid after 14 years? :)
